# Generated by Django 4.1 on 2022-09-05 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_user',
            new_name='id_user',
        ),
    ]
