# Generated by Django 4.1 on 2022-09-06 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile_emailadd_profile_firstname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='relationShip',
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 6, 15, 38, 59, 584213)),
        ),
    ]
