# Generated by Django 4.1 on 2022-09-08 08:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_likepost_remove_profile_emailadd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 8, 13, 48, 32, 690692)),
        ),
    ]
